language: elixir
sudo: required
dist: trusty
git:
  depth: 150
elixir:
  - 1.4
cache: apt
before_install:
  - wget https://github.com/SnappyDataInc/snappydata/releases/download/v0.8/snappydata-0.8-bin.tar.gz
  - tar xvf snappydata-0.8-bin.tar.gz
before_script:
  - echo "localhost -client-bind-address=localhost -J-Djava.net.preferIPv4Stack=true -heap-size=4096m -thrift-framed-transport=true -thrift-server-port=1531 -thrift-binary-protocol=true" | tee -a ./snappydata-0.8-bin/conf/servers
  - echo "localhost -client-bind-address=localhost -J-Djava.net.preferIPv4Stack=true -heap-size=1024m -thrift-framed-transport=true -thrift-server-port=1530 -thrift-binary-protocol=true" | tee -a ./snappydata-0.8-bin/conf/locators
  - echo "localhost -client-bind-address=localhost -J-Djava.net.preferIPv4Stack=true -spray.can.server.parsing.max-content-length=400m -heap-size=4096m" | tee -a ./snappydata-0.8-bin/conf/leads
  - ./snappydata-0.8-bin/sbin/snappy-start-all.sh 
script:
  - mix test test/login_test.exs:16 || true
  - mix test --trace
env:
  global:
    - MIX_ENV=test
