language: elixir
elixir:
  - 1.3.1
cache: apt
before_install:
  - wget https://github.com/SnappyDataInc/snappydata/releases/download/v0.6/snappydata-0.6-bin.tar.gz
  - tar xvf snappydata-0.6-bin.tar.gz
before_script:
  - |
    cat << EOF > ./snappydata-0.6-bin/conf/servers
    localhost -client-bind-address=localhost -J-Duser.timezone=UTC -J-Djava.net.preferIPv4Stack=true  -thrift-server-address=localhost -heap-size=4096m -thrift-server-port=1531 -thrift-binary-protocol=true
    EOF
  - ./snappydata-0.6-bin/sbin/snappy-start-all.sh 
env:
  global:
    - MIX_ENV=snappydata
